name: Check branch with Kubernetes

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
    - "python/**"
    - "!python/packages/autogen-kubernetes/LICENSE-CODE"
    - "!python/packages/autogen-kubernetes/*.md"
    - "!python/.gitignore"

jobs:
  check-with-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: helm/kind-action@v1
        name: Create k8s kind Cluster
        with:
          cluster_name: test-cluster
      - name: Export kubeconfig
        run: |
          kind export kubeconfig --name test-cluster
      - name: Verify kubeconfig and Cluster
        run: |
          kubectl --kubeconfig=$HOME/.kube/config get nodes
      - uses: astral-sh/setup-uv@v3
        name: Setup uv
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.11"
      - name: Run uv sync
        run: |
          uv sync --locked --all-extras
        working-directory: ./python
      - name: check source
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe check
        working-directory: ./python
