name: Check branch with Kubernetes

on:
  workflow_dispatch:
    inputs:
      branches:
        description: "Enter branch to check"
        required: true
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check-with-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: helm/kind-action@v1
        name: Create k8s kind Cluster
      - name: Verify kubeconfig and Cluster
        run: |
          echo "Using kubeconfig at: $KUBECONFIG"
          kubectl get nodes
      - uses: astral-sh/setup-uv@v3
        name: Setup uv
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.11"
      - name: Run uv sync
        run: |
          uv sync --locked --all-extras
        working-directory: ./python
      - name: format check
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe fmt --check
      - name: check source
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe check
        working-directory: ./python
