name: Deploy package

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to deploy'
        required: true
  push:
    tags:
    - "v*"

jobs:
  deploy-package:
    environment:
      name: package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      # Require ref to be a tag
      - run: git show-ref --verify refs/tags/${{ github.event.inputs.ref }}
      - uses: astral-sh/setup-uv@v3
        name: Setup uv
        with:
          enable-cache: true
      - run: uv build --package autogen-kubernetes --out-dir dist/
        name: Build package
        working-directory: python
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
